### ISSUE TITLE
error: cmdModule is not defined

### ISSUE THREAD

**Issue by Seikz** [eemj/broker-watcher#1]
Hello,
i get this error when i run the tera-proxy [proxy] preloading modules

ERROR tera-proxy-game: [dispatch] load: error initializing module "broker-watcher"
error: cmdModule is not defined
    at new BrokerListing (C:\Users\So\Desktop\tera-proxy\bin\node_modules\broker-watcher\index.js:47:19)
    at Dispatch.load (C:\Users\So\Desktop\tera-proxy\node_modules\tera-proxy-game\lib\connection\dispatch\index.js:152:28)
    at Server.net.createServer (C:\Users\So\Desktop\tera-proxy\bin\lib\proxy.js:150:25)

thx

**Comment by eemj** [comment]
Whoops, forgot to rename a variable.. it should be working now.
